[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "benchmarks"
harness = false

[dependencies]
anyhow = "1.0.93"
criterion = "0.5.1"
lazy_static = "1.5.0"
regex = "1.11.1"
